<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>TinyRogues.TrainingDummy</AssemblyName>
    <RootNamespace>TinyRogues.TrainingDummy</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="src/**/*.cs" />
    <Reference Include="BepInEx.Core" HintPath="lib/core/BepInEx.Core.dll" Private="false" />
    <Reference Include="BepInEx.Unity.IL2CPP" HintPath="lib/core/BepInEx.Unity.IL2CPP.dll" Private="false" />
    <Reference Include="Il2CppInterop.Runtime" HintPath="lib/core/Il2CppInterop.Runtime.dll" Private="false" />
    <Reference Include="0Harmony" HintPath="lib/core/0Harmony.dll" Private="false" />

    <Reference Include="Il2Cppmscorlib" HintPath="lib/interop/Il2Cppmscorlib.dll" Private="false" />
    <Reference Include="Il2CppSystem" HintPath="lib/interop/Il2CppSystem.dll" Private="false" />
    <Reference Include="Il2CppSystem.Core" HintPath="lib/interop/Il2CppSystem.Core.dll" Private="false" />

    <Reference Include="Assembly-CSharp" HintPath="lib/interop/Assembly-CSharp.dll" Private="false" />
    <Reference Include="UnityEngine" HintPath="lib/interop/UnityEngine.dll" Private="false" />
    <Reference Include="UnityEngine.CoreModule" HintPath="lib/interop/UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="UnityEngine.IMGUIModule" HintPath="lib/interop/UnityEngine.IMGUIModule.dll" Private="false" />
    <Reference Include="UnityEngine.TextRenderingModule" HintPath="lib/interop/UnityEngine.TextRenderingModule.dll" Private="false" />
    <Reference Include="UnityEngine.InputLegacyModule" HintPath="lib/interop/UnityEngine.InputLegacyModule.dll" Private="false" />
      <Reference Include="Unity.TextMeshPro" HintPath="lib/interop/Unity.TextMeshPro.dll" Private="false" />
    <Reference Include="UnityEngine.TextCoreFontEngineModule" HintPath="lib/interop/UnityEngine.TextCoreFontEngineModule.dll" Private="false" />
    <Reference Include="UnityEngine.TextCoreTextEngineModule" HintPath="lib/interop/UnityEngine.TextCoreTextEngineModule.dll" Private="false" />
      <Reference Include="UnityEngine.UI" HintPath="lib/interop/UnityEngine.UI.dll" Private="false" />
  </ItemGroup>
</Project>
